### ISSUE TITLE
feature: move file to another location

### ISSUE THREAD

**Issue by younger-1** [carlocardella/vscode-FileSystemToolbox#2]
Just like `fileutils.moveFile`.

**Comment by carlocardella** [comment]
Good idea, I'll work on it, thanks for the suggestion 👍

**Comment by carlocardella** [comment]
Release `1.3.0` is available in the Marketplace, let me know if you have other suggestions

**Comment by younger-1** [comment]
Cool! Thank you!

**Comment by younger-1** [comment]
For now, vscode only provide the fullpath of the file when cursor is hover on filename in explorer.
![图片](https://user-images.githubusercontent.com/45989017/168440851-72685f76-0403-4b38-b2f6-cf77dac60d47.png)

Is it possible to show more file info like so. If it is not possible to show this kind of info in file explorer, it is also cool to show this in other appropriate UI element containg filename like breadcrumbs.
![图片](https://user-images.githubusercontent.com/45989017/168440878-3cbba824-5a37-473a-a33c-af64fffac003.png)

**Comment by carlocardella** [comment]
This requires a bit of investigation, let me see what I can do
